/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

// Import Routes

import { Route as rootRoute } from './routes/__root'
import { Route as ContactImport } from './routes/contact'
import { Route as AboutImport } from './routes/about'
import { Route as IndexImport } from './routes/index'
import { Route as HistoryIndexImport } from './routes/history/index'
import { Route as HistoryOurPhilosophyImport } from './routes/history/our-philosophy'
import { Route as HistoryEarlyYearsImport } from './routes/history/early-years'

// Create/Update Routes

const ContactRoute = ContactImport.update({
  id: '/contact',
  path: '/contact',
  getParentRoute: () => rootRoute,
} as any)

const AboutRoute = AboutImport.update({
  id: '/about',
  path: '/about',
  getParentRoute: () => rootRoute,
} as any)

const IndexRoute = IndexImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRoute,
} as any)

const HistoryIndexRoute = HistoryIndexImport.update({
  id: '/history/',
  path: '/history/',
  getParentRoute: () => rootRoute,
} as any)

const HistoryOurPhilosophyRoute = HistoryOurPhilosophyImport.update({
  id: '/history/our-philosophy',
  path: '/history/our-philosophy',
  getParentRoute: () => rootRoute,
} as any)

const HistoryEarlyYearsRoute = HistoryEarlyYearsImport.update({
  id: '/history/early-years',
  path: '/history/early-years',
  getParentRoute: () => rootRoute,
} as any)

// Populate the FileRoutesByPath interface

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexImport
      parentRoute: typeof rootRoute
    }
    '/about': {
      id: '/about'
      path: '/about'
      fullPath: '/about'
      preLoaderRoute: typeof AboutImport
      parentRoute: typeof rootRoute
    }
    '/contact': {
      id: '/contact'
      path: '/contact'
      fullPath: '/contact'
      preLoaderRoute: typeof ContactImport
      parentRoute: typeof rootRoute
    }
    '/history/early-years': {
      id: '/history/early-years'
      path: '/history/early-years'
      fullPath: '/history/early-years'
      preLoaderRoute: typeof HistoryEarlyYearsImport
      parentRoute: typeof rootRoute
    }
    '/history/our-philosophy': {
      id: '/history/our-philosophy'
      path: '/history/our-philosophy'
      fullPath: '/history/our-philosophy'
      preLoaderRoute: typeof HistoryOurPhilosophyImport
      parentRoute: typeof rootRoute
    }
    '/history/': {
      id: '/history/'
      path: '/history'
      fullPath: '/history'
      preLoaderRoute: typeof HistoryIndexImport
      parentRoute: typeof rootRoute
    }
  }
}

// Create and export the route tree

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/contact': typeof ContactRoute
  '/history/early-years': typeof HistoryEarlyYearsRoute
  '/history/our-philosophy': typeof HistoryOurPhilosophyRoute
  '/history': typeof HistoryIndexRoute
}

export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/contact': typeof ContactRoute
  '/history/early-years': typeof HistoryEarlyYearsRoute
  '/history/our-philosophy': typeof HistoryOurPhilosophyRoute
  '/history': typeof HistoryIndexRoute
}

export interface FileRoutesById {
  __root__: typeof rootRoute
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/contact': typeof ContactRoute
  '/history/early-years': typeof HistoryEarlyYearsRoute
  '/history/our-philosophy': typeof HistoryOurPhilosophyRoute
  '/history/': typeof HistoryIndexRoute
}

export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/about'
    | '/contact'
    | '/history/early-years'
    | '/history/our-philosophy'
    | '/history'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/about'
    | '/contact'
    | '/history/early-years'
    | '/history/our-philosophy'
    | '/history'
  id:
    | '__root__'
    | '/'
    | '/about'
    | '/contact'
    | '/history/early-years'
    | '/history/our-philosophy'
    | '/history/'
  fileRoutesById: FileRoutesById
}

export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AboutRoute: typeof AboutRoute
  ContactRoute: typeof ContactRoute
  HistoryEarlyYearsRoute: typeof HistoryEarlyYearsRoute
  HistoryOurPhilosophyRoute: typeof HistoryOurPhilosophyRoute
  HistoryIndexRoute: typeof HistoryIndexRoute
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AboutRoute: AboutRoute,
  ContactRoute: ContactRoute,
  HistoryEarlyYearsRoute: HistoryEarlyYearsRoute,
  HistoryOurPhilosophyRoute: HistoryOurPhilosophyRoute,
  HistoryIndexRoute: HistoryIndexRoute,
}

export const routeTree = rootRoute
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

/* ROUTE_MANIFEST_START
{
  "routes": {
    "__root__": {
      "filePath": "__root.tsx",
      "children": [
        "/",
        "/about",
        "/contact",
        "/history/early-years",
        "/history/our-philosophy",
        "/history/"
      ]
    },
    "/": {
      "filePath": "index.tsx"
    },
    "/about": {
      "filePath": "about.tsx"
    },
    "/contact": {
      "filePath": "contact.tsx"
    },
    "/history/early-years": {
      "filePath": "history/early-years.tsx"
    },
    "/history/our-philosophy": {
      "filePath": "history/our-philosophy.tsx"
    },
    "/history/": {
      "filePath": "history/index.tsx"
    }
  }
}
ROUTE_MANIFEST_END */
